{% set version = "1.2" %}

{% set posix = 'm2-' if win else '' %}

package:
  name: r-rapport
  version: {{ version|replace("-", "_") }}

source:
  fn: rapport_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/rapport_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/rapport/rapport_{{ version }}.tar.gz
  sha256: a435695cb41a532e25278f09dd150a94c0990193cd849a9df485002d09ab15ad

build:
  noarch: generic
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-pander
    - r-rapportools
    - r-stringr
    - r-yaml
    - pandoc

  run:
    - r-base
    - r-pander
    - r-rapportools
    - r-stringr
    - r-yaml
    - pandoc

test:
  commands:
    - $R -e "library('rapport')"  # [not win]
    - "\"%R%\" -e \"library('rapport')\""  # [win]

about:
  home: http://rapport-package.info/
  license: AGPL-3.0-only
  summary: Facilitating the creation of reproducible statistical report templates. Once created, rapport templates can be exported to various external formats (HTML, LaTeX, PDF, ODT etc.) with pandoc as the converter backend.
  license_family: AGPL

  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/AGPL-3
extra:
  recipe-maintainers:
    - conda-forge/r
