appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: lrM6mJEMtLgv/d4csEVwYpR0UDVJUblWxzT8X9dAi9gptvDn9+NwELd41XeJcvaykssIi7wwqoOmIl/iNfBru+lL53IZD/MwmVW3k2B4J0KiWxPySExWvivsNYJTw1nDhcfCPyhi3E3GfJyREPY0cTcslcKG33VpjsROlbK/I8sg4EsvPphyUE2cF7EDCIVX1OgLmJO7ikkgWAWA6T3kQRgylpKsct1R28Y//FR60YciOogOqq5xa5Pvsd7bx0QlulES1fojzI0gxeDsetCuAMtK7VISrED0PSoZKdusVPjYJb/bPDYxK8SQzdiyiPrSzBT0kr0rNsyC6Tw3RkSpNf9l7vQ2pRo/Tsz8RLAjgt6JD4wGiVjzQZYVBSVlw8hqYWNGAdoY/v7U/HSp3JNnjQg0n2qRn89Upxyjkr2WfMN/m22BvtRthhgAE4e4wwlWGmUBEyqEIe47GZDQiTtaZmf0DJHhxJt0/ZqR/nYSejBDDySYBFoS2KDRdmScfVdrX8aRsjL5Ex2+f42KVNrmj9FOAwT//vbXfDSXA3Ar2cZ+ZatxFEsJaZwqfKQ9lWVr2jPHA+1ld8oqLqywKL9tyC/ZJkfVoHHPTdNvnAQOYGd/KnwMVbhuXH6QilbciVgjfbionFU2dYaJF4YuOgQ4gaZ7SokMy9A11sYgHl6kyew=}
bot:
  automerge: true
