travis:
  secure:
    BINSTAR_TOKEN: cmeusOqcjLCMtM7TcZG593arN7Wi502qCT9fTQLqF0CmlZxpggsz5Iecv62PdVB9pp5eJa6MVYlXiHfStC0pXq1Nm26lU7UTODcuFeAbIm2DmlqEq1Xzqofdqq5E2CnwZgsC0Zl+eGIg1RXtKJCo6S29gtbtFjPqLtIgzlf9aNOzQdEWBuZrUWk4+lbEUZwnaq3Sp/zZHP3zQfX5yDKKSARbNunkLhAr7FprLEc4MBMcJlEL5ljlr+N3rH9HK28SSl+Hxm7V1nSuURdI6A3Ne0+SA5v55+9SKsRIzQBnABwyuDNggrdR7nx3dwlYcFTnBzH9p9k7SlRyF467SrEfCXkgKSV1ivKGmyu7E8a+A88KVTjTgfYrwwd7vtcow7N0xqOz5WjAwSMRsnHr9CNHvl23J6UBoGm2F3Q98q1zHGpRjxunYk2mvq8LeyW5xSVAqKp9YVoklV8qxqKAAY/t0EZnxpFGdhYMINsJHxrlqlqmH8zeQM/IofgjwhKBn9yL4wrImO12zBneLrDne0BEtbTLcvHs1jdkBW6jyEnKCA38NRzjng4TtpOyt8Mfej9dNvdgFars/kTyqKhIV7386eli4LLAePRvqdJRw+s8LxOy82qkdACZJfWmOqjrgmPgj17rzU6n/vyfj5pVWWp2mZbKd/vVJd+0iG29ArSppys=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
